<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="Empower132" name="TestNG.DependsonMethodConcept" tests="3" failures="0" timestamp="06 Apr 2021 14:19:18 GMT" time="0.025" errors="1">
  <testcase name="checkProdTest" time="0.019" classname="TestNG.DependsonMethodConcept"/>
  <testcase name="loginTest" time="0.003" classname="TestNG.DependsonMethodConcept">
    <error type="org.testng.TestException" message="
Method DependsonMethodConcept.loginTest()[pri:0, instance:TestNG.DependsonMethodConcept@523884b2] should have thrown an exception of any of types [class java.lang.NullPointerException, class java.lang.ArithmeticException]">
      <![CDATA[org.testng.TestException: 
Method DependsonMethodConcept.loginTest()[pri:0, instance:TestNG.DependsonMethodConcept@523884b2] should have thrown an exception of any of types [class java.lang.NullPointerException, class java.lang.ArithmeticException]
at org.testng.internal.ExpectedExceptionsHolder.noException(ExpectedExceptionsHolder.java:80)
at org.testng.internal.Invoker.considerExceptions(Invoker.java:1140)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:615)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- loginTest -->
  <testcase name="searchProdTest" time="0.003" classname="TestNG.DependsonMethodConcept"/>
</testsuite> <!-- TestNG.DependsonMethodConcept -->
